// Generated by scripts/sync-portfolio-assets.mjs — do not edit by hand.

export type PortfolioProjectGenerated = {
  id: string;
  slug: string;
  title: string;
  category: string;
  projectType: string;
  location: string;
  scope: string;
  completion: string;
  description: string;
  images: string[];
};

export const PORTFOLIO_PROJECTS_GENERATED: PortfolioProjectGenerated[] = [
  {
    "id": "123-corwin-bathroom",
    "slug": "123-corwin-bathroom",
    "title": "123 Corwin Street · Bathroom",
    "category": "Residential bath",
    "projectType": "Residential remodel",
    "location": "Bay Area, CA",
    "scope": "Full bathroom renovation, custom tile, fixture integration",
    "completion": "Recent project",
    "description": "A curated look at the craftsmanship, finish quality, and project execution behind this Pristine Construction project.",
    "images": [
      "/portfolio/123-corwin-bathroom/001_1-print-slavablazerphotography_1.jpg",
      "/portfolio/123-corwin-bathroom/002_2-print-slavablazerphotography_2.jpg",
      "/portfolio/123-corwin-bathroom/003_3-print-slavablazerphotography_3.jpg",
      "/portfolio/123-corwin-bathroom/004_4-print-slavablazerphotography_4.jpg",
      "/portfolio/123-corwin-bathroom/005_5-print-slavablazerphotography_5.jpg",
      "/portfolio/123-corwin-bathroom/006_6-print-slavablazerphotography_6.jpg",
      "/portfolio/123-corwin-bathroom/007_7-print-slavablazerphotography_7.jpg",
      "/portfolio/123-corwin-bathroom/008_8-print-slavablazerphotography_8.jpg",
      "/portfolio/123-corwin-bathroom/009_9-print-slavablazerphotography_9.jpg",
      "/portfolio/123-corwin-bathroom/010_10-print-slavablazerphotography_10.jpg",
      "/portfolio/123-corwin-bathroom/011_11-print-slavablazerphotography_11.jpg",
      "/portfolio/123-corwin-bathroom/012_12-print-slavablazerphotography_12.jpg",
      "/portfolio/123-corwin-bathroom/013_13-print-slavablazerphotography_13.jpg",
      "/portfolio/123-corwin-bathroom/014_14-print-slavablazerphotography_14.jpg",
      "/portfolio/123-corwin-bathroom/015_15-print-slavablazerphotography_15.jpg",
      "/portfolio/123-corwin-bathroom/016_16-print-slavablazerphotography_16.jpg",
      "/portfolio/123-corwin-bathroom/017_17-print-slavablazerphotography_17.jpg",
      "/portfolio/123-corwin-bathroom/018_18-print-slavablazerphotography_18.jpg",
      "/portfolio/123-corwin-bathroom/019_19-print-slavablazerphotography_19.jpg"
    ]
  },
  {
    "id": "466-benvenue-adu",
    "slug": "466-benvenue-adu",
    "title": "466 Benvenue · Accessory dwelling",
    "category": "New ADU",
    "projectType": "Residential — ADU",
    "location": "Bay Area, CA",
    "scope": "Design-build ADU — structure, envelope, interior build-out",
    "completion": "Recent project",
    "description": "A curated look at the craftsmanship, finish quality, and project execution behind this Pristine Construction project.",
    "images": [
      "/portfolio/466-benvenue-adu/001_dsc02103.jpg",
      "/portfolio/466-benvenue-adu/002_dji_20250809143756_0647_d.jpg",
      "/portfolio/466-benvenue-adu/003_dji_20250809144403_0657_d-2.jpg",
      "/portfolio/466-benvenue-adu/004_dji_20250809150349_0698_d.jpg",
      "/portfolio/466-benvenue-adu/005_dsc02104.jpg",
      "/portfolio/466-benvenue-adu/006_dsc02105.jpg",
      "/portfolio/466-benvenue-adu/007_dsc02109.jpg",
      "/portfolio/466-benvenue-adu/008_dsc02115.jpg",
      "/portfolio/466-benvenue-adu/009_dsc02129-3.jpg",
      "/portfolio/466-benvenue-adu/010_dsc02131-2.jpg",
      "/portfolio/466-benvenue-adu/011_dsc02136-4.jpg",
      "/portfolio/466-benvenue-adu/012_dsc02142.jpg",
      "/portfolio/466-benvenue-adu/013_dsc02143.jpg",
      "/portfolio/466-benvenue-adu/014_dsc02144-2.jpg",
      "/portfolio/466-benvenue-adu/015_dsc02150.jpg",
      "/portfolio/466-benvenue-adu/016_dsc02151.jpg",
      "/portfolio/466-benvenue-adu/017_dsc02172.jpg",
      "/portfolio/466-benvenue-adu/018_dsc02176.jpg",
      "/portfolio/466-benvenue-adu/019_dsc02180.jpg",
      "/portfolio/466-benvenue-adu/020_dsc02183.jpg",
      "/portfolio/466-benvenue-adu/021_dsc02184.jpg",
      "/portfolio/466-benvenue-adu/022_dsc02199.jpg",
      "/portfolio/466-benvenue-adu/023_dsc02209.jpg",
      "/portfolio/466-benvenue-adu/024_dsc02225.jpg",
      "/portfolio/466-benvenue-adu/025_dsc02240.jpg",
      "/portfolio/466-benvenue-adu/026_dsc02243.jpg",
      "/portfolio/466-benvenue-adu/027_dsc02247.jpg",
      "/portfolio/466-benvenue-adu/028_dsc02251.jpg",
      "/portfolio/466-benvenue-adu/029_dsc02265.jpg",
      "/portfolio/466-benvenue-adu/030_dsc02271-2.jpg"
    ]
  },
  {
    "id": "california-street",
    "slug": "california-street",
    "title": "California Street",
    "category": "Interior architecture",
    "projectType": "Residential remodel",
    "location": "Bay Area, CA",
    "scope": "Interior renovation, lighting, bespoke details",
    "completion": "Recent project",
    "description": "A curated look at the craftsmanship, finish quality, and project execution behind this Pristine Construction project.",
    "images": [
      "/portfolio/california-street/001_spoof-1-of-9.jpg",
      "/portfolio/california-street/002_spoof-2-of-9.jpg",
      "/portfolio/california-street/003_spoof-3-of-9.jpg",
      "/portfolio/california-street/004_spoof-4-of-9.jpg",
      "/portfolio/california-street/005_spoof-5-of-9.jpg",
      "/portfolio/california-street/006_spoof-6-of-9.jpg",
      "/portfolio/california-street/007_spoof-7-of-9.jpg",
      "/portfolio/california-street/008_spoof-8-of-9.jpg",
      "/portfolio/california-street/009_spoof-9-of-9.jpg"
    ]
  },
  {
    "id": "corwin-street",
    "slug": "corwin-street",
    "title": "Corwin Street",
    "category": "Residential",
    "projectType": "Residential remodel",
    "location": "Bay Area, CA",
    "scope": "Interior renovation, finish work, spatial refinement",
    "completion": "Recent project",
    "description": "A curated look at the craftsmanship, finish quality, and project execution behind this Pristine Construction project.",
    "images": [
      "/portfolio/corwin-street/001_spoof-1-of-11.jpg",
      "/portfolio/corwin-street/002_spoof-2-of-11.jpg",
      "/portfolio/corwin-street/003_spoof-3-of-11.jpg",
      "/portfolio/corwin-street/004_spoof-4-of-11.jpg",
      "/portfolio/corwin-street/005_spoof-5-of-11.jpg",
      "/portfolio/corwin-street/006_spoof-6-of-11.jpg",
      "/portfolio/corwin-street/007_spoof-7-of-11.jpg",
      "/portfolio/corwin-street/008_spoof-8-of-11.jpg",
      "/portfolio/corwin-street/009_spoof-9-of-11.jpg",
      "/portfolio/corwin-street/010_spoof-10-of-11.jpg",
      "/portfolio/corwin-street/011_spoof-11-of-11.jpg"
    ]
  },
  {
    "id": "drake-street",
    "slug": "drake-street",
    "title": "Drake Street",
    "category": "Residential",
    "projectType": "Residential remodel",
    "location": "Bay Area, CA",
    "scope": "Open plan refinement, kitchen and living zones",
    "completion": "Recent project",
    "description": "A curated look at the craftsmanship, finish quality, and project execution behind this Pristine Construction project.",
    "images": [
      "/portfolio/drake-street/001_spoof-3-of-7.jpg",
      "/portfolio/drake-street/002_dsc09053-hdr.jpg",
      "/portfolio/drake-street/003_dsc09062-hdr.jpg",
      "/portfolio/drake-street/004_dsc09074-hdr.jpg",
      "/portfolio/drake-street/005_spoof-1-of-7.jpg",
      "/portfolio/drake-street/006_spoof-2-of-7.jpg",
      "/portfolio/drake-street/007_spoof-4-of-7.jpg",
      "/portfolio/drake-street/008_spoof-5-of-7.jpg",
      "/portfolio/drake-street/009_spoof-6-of-7.jpg",
      "/portfolio/drake-street/010_spoof-7-of-7.jpg"
    ]
  },
  {
    "id": "ellsworth-whole-house",
    "slug": "ellsworth-whole-house",
    "title": "Ellsworth Street · Whole house",
    "category": "Whole house",
    "projectType": "Whole-home remodel",
    "location": "Bay Area, CA",
    "scope": "Full interior program — planning, build, finishes",
    "completion": "Recent project",
    "description": "A curated look at the craftsmanship, finish quality, and project execution behind this Pristine Construction project.",
    "images": [
      "/portfolio/ellsworth-whole-house/001_dsc08761.jpg",
      "/portfolio/ellsworth-whole-house/002_dsc08793.jpg",
      "/portfolio/ellsworth-whole-house/003_dsc08796.jpg",
      "/portfolio/ellsworth-whole-house/004_dsc08814.jpg",
      "/portfolio/ellsworth-whole-house/005_dsc08869.jpg",
      "/portfolio/ellsworth-whole-house/006_dsc08900.jpg",
      "/portfolio/ellsworth-whole-house/007_dsc08910.jpg",
      "/portfolio/ellsworth-whole-house/008_dsc08941.jpg",
      "/portfolio/ellsworth-whole-house/009_dsc08981.jpg",
      "/portfolio/ellsworth-whole-house/010_dsc09017.jpg",
      "/portfolio/ellsworth-whole-house/011_dsc09058.jpg",
      "/portfolio/ellsworth-whole-house/012_dsc09134.jpg",
      "/portfolio/ellsworth-whole-house/013_dsc09138.jpg",
      "/portfolio/ellsworth-whole-house/014_dsc09144.jpg",
      "/portfolio/ellsworth-whole-house/015_dsc09147.jpg",
      "/portfolio/ellsworth-whole-house/016_dsc09162.jpg"
    ]
  },
  {
    "id": "selected-residential-work",
    "slug": "selected-residential-work",
    "title": "Selected residential work",
    "category": "Editorial",
    "projectType": "Residential — multiple",
    "location": "Bay Area, CA",
    "scope": "Curated interiors across distinct projects and scopes",
    "completion": "Recent work",
    "description": "A curated look at the craftsmanship, finish quality, and project execution behind this Pristine Construction project.",
    "images": [
      "/portfolio/selected-residential-work/001_spoof-1-of-10.jpg",
      "/portfolio/selected-residential-work/002_dsc00153-hdr.jpg",
      "/portfolio/selected-residential-work/003_dsc00198-hdr.jpg",
      "/portfolio/selected-residential-work/004_dsc00201-hdr.jpg",
      "/portfolio/selected-residential-work/005_dsc00213-hdr.jpg",
      "/portfolio/selected-residential-work/006_dsc00219-hdr.jpg",
      "/portfolio/selected-residential-work/007_dsc00225-hdr.jpg",
      "/portfolio/selected-residential-work/008_dsc00234-hdr.jpg",
      "/portfolio/selected-residential-work/009_dsc06760-hdr.jpg",
      "/portfolio/selected-residential-work/010_dsc09053-hdr.jpg",
      "/portfolio/selected-residential-work/011_dsc09062-hdr.jpg",
      "/portfolio/selected-residential-work/012_dsc09074-hdr.jpg",
      "/portfolio/selected-residential-work/013_spoof-1-of-7.jpg",
      "/portfolio/selected-residential-work/014_spoof-2-of-7.jpg",
      "/portfolio/selected-residential-work/015_spoof-2-of-10.jpg",
      "/portfolio/selected-residential-work/016_spoof-2-of-32.jpg",
      "/portfolio/selected-residential-work/017_spoof-3-of-7.jpg",
      "/portfolio/selected-residential-work/018_spoof-3-of-10.jpg",
      "/portfolio/selected-residential-work/019_spoof-3-of-32.jpg",
      "/portfolio/selected-residential-work/020_spoof-4-of-7.jpg",
      "/portfolio/selected-residential-work/021_spoof-4-of-32.jpg",
      "/portfolio/selected-residential-work/022_spoof-5-of-32.jpg",
      "/portfolio/selected-residential-work/023_spoof-6-of-32.jpg",
      "/portfolio/selected-residential-work/024_spoof-7-of-32.jpg",
      "/portfolio/selected-residential-work/025_spoof-26-of-32.jpg"
    ]
  },
  {
    "id": "nelson-court",
    "slug": "nelson-court",
    "title": "Nelson Court",
    "category": "Residential",
    "projectType": "Residential remodel",
    "location": "Bay Area, CA",
    "scope": "Interior renovation, custom details, finish quality",
    "completion": "Recent project",
    "description": "A curated look at the craftsmanship, finish quality, and project execution behind this Pristine Construction project.",
    "images": [
      "/portfolio/nelson-court/001_dsc06718-hdr-edit.jpg",
      "/portfolio/nelson-court/002_dsc06679-hdr-edit-3.jpg",
      "/portfolio/nelson-court/003_dsc06688-hdr-edit-2.jpg",
      "/portfolio/nelson-court/004_dsc06691-hdr.jpg",
      "/portfolio/nelson-court/005_dsc06697-hdr.jpg",
      "/portfolio/nelson-court/006_dsc06706-hdr.jpg",
      "/portfolio/nelson-court/007_dsc06712-hdr.jpg",
      "/portfolio/nelson-court/008_dsc06724-hdr.jpg",
      "/portfolio/nelson-court/009_dsc06730-hdr.jpg",
      "/portfolio/nelson-court/010_dsc06745-hdr.jpg",
      "/portfolio/nelson-court/011_dsc06757-hdr-edit.jpg",
      "/portfolio/nelson-court/012_dsc06760-hdr.jpg"
    ]
  }
];
